board/urls.py
from django.urls import path
from .views import base_views, post_views, comment_views


app_name = "board"

urlpatterns = [
    # base_views.py
    path("", base_views.index, name="index"),
    path("<int:post_id>/", base_views.detail, name="detail"),
    # post_views.py
    path("post/create/", post_views.post_create, name="post_create"),
    path(
        "post/modify/<int:post_id>/",
        post_views.post_modify,
        name="post_modify",
    ),
    path(
        "post/delete/<int:post_id>/",
        post_views.post_delete,
        name="post_delete",
    ),
    path('post/vote/<int:post_id>/', post_views.post_vote, name='post_vote'),
    # comment_views.py
    path(
        "comment/create/<int:post_id>/",
        comment_views.comment_create,
        name="comment_create",
    ),
    path(
        "comment/modify/<int:comment_id>/",
        comment_views.comment_modify,
        name="comment_modify",
    ),
    path(
        "comment/delete/<int:comment_id>/",
        comment_views.comment_delete,
        name="comment_delete",
    ),
    path('comment/vote/<int:comment_id>/', comment_views.comment_vote, name='comment_vote'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "board/", include("board.urls")
    ),  # board로 시작하는 페이지 요청 시, board/urls.py을 읽어서 처리
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),  # '/' 에 해당되는 path
]

handler404 = 'common.views.page_not_found'

board/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Post
from django.db.models import Q


def index(request):
    page = request.GET.get("page", "1")  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    post_list = Post.objects.order_by("-create_date")

    if kw:
        # subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(comment__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(comment__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    paginator = Paginator(post_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {"post_list": page_obj, 'page': page, 'kw': kw}
    return render(request, "board/post_list.html", context)


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {"post": post}
    return render(request, "board/post_detail.html", context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <!-- board CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, django project!</title>
  </head>
  <body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    {% block content %} {% endblock %}
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %} {% endblock %}
    <!-- 자바스크립트 End -->
  </body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<style>
  #logout-form {
    display: inline;
  }
  #logout-form button {
    background: none;
    border: none;
    cursor: pointer;
    padding: 0;
    {% comment %} text-decoration: underline; {% endcomment %}
  }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'board:index' %}">게시판</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% comment %} 현재 사용자가 로그인 되었는지를 판별 {% endcomment %}
        <li class="nav-item">
          {% if user.is_authenticated %} {% comment %}
          <a class="nav-link" href="{% url 'common:logout' %}"
            >{{ user.username }} (로그아웃)</a
          >
          {% endcomment %}
          <form
            id="logout-form"
            method="post"
            action="{% url 'common:logout' %}"
          >
            {% csrf_token %}
            <button type="submit">{{ user.username }} (로그아웃)</button>
          </form>
          {% else %}
          <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
        <li>
          {% if not user.is_authenticated %}
          <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>