board/urls.py
from django.urls import path
from .views import base_views, post_views, comment_views


app_name = "board"

urlpatterns = [
    # base_views.py
    path("", base_views.index, name="index"),
    path("<int:post_id>/", base_views.detail, name="detail"),
    # post_views.py
    path("post/create/", post_views.post_create, name="post_create"),
    path(
        "post/modify/<int:post_id>/",
        post_views.post_modify,
        name="post_modify",
    ),
    path(
        "post/delete/<int:post_id>/",
        post_views.post_delete,
        name="post_delete",
    ),
    path('post/vote/<int:post_id>/', post_views.post_vote, name='post_vote'),
    # comment_views.py
    path(
        "comment/create/<int:post_id>/",
        comment_views.comment_create,
        name="comment_create",
    ),
    path(
        "comment/modify/<int:comment_id>/",
        comment_views.comment_modify,
        name="comment_modify",
    ),
    path(
        "comment/delete/<int:comment_id>/",
        comment_views.comment_delete,
        name="comment_delete",
    ),
    path('comment/vote/<int:comment_id>/', comment_views.comment_vote, name='comment_vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "board/", include("board.urls")
    ),  # board로 시작하는 페이지 요청 시, board/urls.py을 읽어서 처리
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),  # '/' 에 해당되는 path
]

handler404 = 'common.views.page_not_found'

board/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_post')  # 추천인 추가

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')

board/forms.py
from django import forms
from board.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post  # 사용할 모델
        fields = ["subject", "content"]  # PostForm에서 사용할 Post 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        } 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

board/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Post
from django.db.models import Q


def index(request):
    page = request.GET.get("page", "1")  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    post_list = Post.objects.order_by("-create_date")

    if kw:
        # subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(comment__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(comment__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()

    paginator = Paginator(post_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {"post_list": page_obj, 'page': page, 'kw': kw}
    return render(request, "board/post_list.html", context)


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {"post": post}
    return render(request, "board/post_detail.html", context)

board/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import Post, Comment
from ..forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# request.user에는 로그아웃 상태이면 AnonymousUser 객체가, 로그인 상태이면 User 객체가 들어있다.
# @login_required 애너테이션이 붙은 함수는 로그인이 필요한 함수를 의미한다.
@login_required(login_url="common:login")
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user  # author 속성에 로그인 계정 저장
            comment.create_date = timezone.now()
            comment.post = post
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('board:detail', post_id=post.id), comment.id))
    else:
        return redirect("board:detail", post_id=post.id)
    context = {"post": post, "form": form}
    return render(request, "board/post_detail.html", context)


@login_required(login_url="common:login")
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("board:detail", post_id=comment.post.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('board:detail', post_id=comment.post.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {"comment": comment, "form": form}
    return render(request, "board/comment_form.html", context)


@login_required(login_url="common:login")
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, "삭제권한이 없습니다")
    else:
        comment.delete()
    return redirect("board:detail", post_id=comment.post.id)


@login_required(login_url='common:login')
def comment_vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(
                resolve_url('board:detail', post_id=comment.post.id), comment.id))

board/views/post_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..models import Post
from ..forms import PostForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url="common:login")
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user  # author 속성에 로그인 계정 저장
            post.create_date = timezone.now()
            post.save()
            return redirect("board:index")
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "board/post_form.html", context)


@login_required(login_url="common:login")
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, "수정권한이 없습니다")
        return redirect("board:detail", post_id=post.id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.modify_date = timezone.now()  # 수정일시 저장
            post.save()
            return redirect("board:detail", post_id=post.id)
    else:
        form = PostForm(instance=post)
    context = {"form": form}
    return render(request, "board/post_form.html", context)


@login_required(login_url="common:login")
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, "삭제권한이 없습니다")
        return redirect("board:detail", post_id=post.id)
    post.delete()
    return redirect("board:index")


@login_required(login_url='common:login')
def post_vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        # voter는 여러사람을 추가할 수 있는 ManyToManyField이므로 add 함수를 사용하여 추천인을 추가한다.
        # 중복 추가는 ManyToManyField 내부에서 자체적으로 처리돼서 적용되지 않는다.
        post.voter.add(request.user)
    return redirect('board:detail', post_id=post.id)

templates/board/comment_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/post_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container my-3">
  <!-- message 표시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul>
      <li>{{ message.message }}</li>
    </ul>
    {% endfor %}
  </div>
  {% endif %}
  <!-- 게시글 -->
  <h2 class="border-bottom py-2">{{ post.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text">
        {{ post.content|mark }}
      </div>
      <div class="d-flex justify-content-end">
        {% if post.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">modified at</div>
          <div>{{ post.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ post.author.username }}</div>
          <div>{{ post.create_date }}</div>
        </div>
      </div>
      <div class="my-3">
        <a href="javascript:void(0)" data-uri="{% url 'board:post_vote' post.id  %}"
        class="recommend btn btn-sm btn-outline-secondary"> 추천
         <span class="badge rounded-pill bg-success">{{post.voter.count}}</span>
        </a>
        {% if request.user == post.author %}
        <a
          href="{% url 'board:post_modify' post.id  %}"
          class="btn btn-sm btn-outline-secondary"
          >수정</a
        >
        <a
          href="javascript:void(0)"
          class="delete btn btn-sm btn-outline-secondary"
          data-uri="{% url 'board:post_delete' post.id  %}"
          >삭제</a
        >
        {% endif %}
      </div>
    </div>
  </div>
  <!-- 댓글 -->
  <h5 class="border-bottom my-3 py-2">
    {{post.comment_set.count}}개의 댓글이 있습니다.
  </h5>
  {% for comment in post.comment_set.all %}
  <a id="comment_{{ comment.id }}"></a>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text">
        {{ comment.content|mark }}
      </div>
      <div class="d-flex justify-content-end">
        {% if comment.modify_date %}
        <div class="badge bg-light text-dark p-2 text-start mx-3">
          <div class="mb-2">modified at</div>
          <div>{{ comment.modify_date }}</div>
        </div>
        {% endif %}
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ comment.author.username }}</div>
          <div>{{ comment.create_date }}</div>
        </div>
      </div>
      <div class="my-3">
        <a href="javascript:void(0)" data-uri="{% url 'board:comment_vote' comment.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{comment.voter.count}}</span>
        </a>
        {% if request.user == comment.author %}
        <a
          href="{% url 'board:comment_modify' comment.id  %}"
          class="btn btn-sm btn-outline-secondary"
          >수정</a
        >
        <a
          href="#"
          class="delete btn btn-sm btn-outline-secondary"
          data-uri="{% url 'board:comment_delete' comment.id  %}"
          >삭제</a
        >
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
  <!-- 댓글 등록 -->
  <form
    action="{% url 'board:comment_create' post.id %}"
    method="post"
    class="my-3"
  >
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} {% if field.errors %}
      <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
      </div>
      {% endif %} {% endfor %}
    </div>
    {% endif %}
    <div class="mb-3">
      <label for="content" class="form-label">댓글 내용</label>
      <textarea
        {%
        if
        not
        user.is_authenticated
        %}disabled{%
        endif
        %}
        name="content"
        id="content"
        class="form-control"
        rows="10"
      ></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary" />
  </form>
</div>
{% endblock %} {% block script %}
<script type="text/javascript">
  const delete_elements = document.getElementsByClassName("delete");
  Array.from(delete_elements).forEach(function (element) {
    element.addEventListener("click", function () {
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = this.dataset.uri;
      }
    });
  });
  const recommend_elements = document.getElementsByClassName("recommend");
  Array.from(recommend_elements).forEach(function(element) {
      element.addEventListener('click', function() {
          if(confirm("정말로 추천하시겠습니까?")) {
              location.href = this.dataset.uri;
          };
      });
  });
</script>
{% endblock %}

templates/board/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">게시글등록</h5>
  <form method="post">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
      {% if field.errors %}
      <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
      </div>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="mb-3">
      <label for="subject" class="form-label">제목</label>
      <input
        type="text"
        class="form-control"
        name="subject"
        id="subject"
        value="{{ form.subject.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">
{{ form.content.value|default_if_none:'' }}</textarea
      >
    </div>
    <button type="submit" class="btn btn-primary">등록하기</button>
  </form>
</div>
{% endblock %}

templates/board/post_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<style>
  a {
    color: inherit;
    text-decoration: none;
  }
</style>
<div class="container my-3">
  <div class="row my-3">
    <div class="col-6">
        <a href="{% url 'board:post_create' %}" class="btn btn-primary">게시글 등록하기</a>
    </div>
    <div class="col-6">
        <div class="input-group">
            <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr class="text-center table-dark">
        <th>번호</th>
        <th style="width:50%">제목</th>
        <th>글쓴이</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if post_list %}
      {% for post in post_list %}
      <tr class="text-center">
        <td>
            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td class="text-center">
          <a href="{% url 'board:detail' post.id %}">{{ post.subject }}</a>
          {% if post.comment_set.count > 0 %}
          <span class="text-danger small mx-2">{{ post.comment_set.count }}</span>
          {% endif %}
        </td>
        <td>{{ post.author.username }}</td>  <!-- 글쓴이 추가 -->
        <td>{{ post.create_date }}</td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td colspan="4">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if post_list.has_previous %}
    <li class="page-item">
      <a class="page-link" data-page="{{ post_list.previous_page_number }}"
      href="javascript:void(0)">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in post_list.paginator.page_range %}
    {% if page_number >= post_list.number|add:-2 and page_number <= post_list.number|add:2 %}
    {% if page_number == post_list.number %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" data-page="{{ page_number }}"
      href="javascript:void(0)">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if post_list.has_next %}
    <li class="page-item">
      <a class="page-link" data-page="{{ post_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}